services:
  db:
    image: postgres:16
    user: root
    environment:
      - POSTGRES_USER=odoo
      - POSTGRES_PASSWORD=odoo17@2023
      - POSTGRES_DB=postgres
    restart: always # run as a service
    ports:
      - "5432:5432"
    volumes:
      - ./postgresql:/var/lib/postgresql/data
    networks:
      - learn_odoo_17

  odoo17:
    image: odoo:17
    user: root
    depends_on:
      - db
    ports:
      - "10017:8069"
      - "20017:8072" # live chat
    tty: true
    # 1. Basic
    # command: --
    # 2.useful when don't know dev model, work well when error _unknown id
    # command: odoo -d learn_odoo_17 --dev=xml,reload
    # 3. not recommend just sometime error when use m2o, o2m, m2m when -u <...>
    command: odoo -u qweb_pdf_report -d learn_odoo_17 --dev=all
    environment:
      - HOST=db
      - USER=odoo
      - PASSWORD=odoo17@2023
    volumes:
      #- /etc/timezone:/etc/timezone:ro
      #- /etc/localtime:/etc/localtime:ro
      #- ./entrypoint.sh:/entrypoint.sh   # if you want to install additional Python packages, uncomment this line!
      - ./addons:/mnt/extra-addons
      - ./etc:/etc/odoo
    restart: always # run as a service
    networks:
      - learn_odoo_17
networks:
  learn_odoo_17:
    driver: bridge
