[tool.ruff]
line-length = 80
target-version = "py38"  # Adjust based on your Odoo version
select = [
    "E", "F", "W", "I",  # PEP8, Pyflakes, Warnings, Import sorting
    "UP", "PL", "B", "A"  # Upgrade, Pylint, Bugbear, Built-in checks
]
ignore = ["E501"]  # Ignore long lines (Odoo often has long SQL queries)
fix = true
